version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '4000:4000'
    links:
      - mongo
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
